name = "aiconclave"
account_id = "8784dd7883d1306d209b61ff4a0f5d1c"
compatibility_date = "2026-07-25"
pages_build_output_dir = "publish"

[[d1_databases]]
binding = "DB"
database_name = "aiconclave-registrations"
database_id = "cfc0669f-3de7-4429-ab54-686e966bb56b"
preview_database_id = "DB"
